### ISSUE TITLE
A question about training with RGB images

### ISSUE THREAD

**Issue by Vandermode** [juglab/n2v#3]
Hi, nice work. I look at the example 2D and find you augment data with shape `N x H x W x 1` by a mask such that the final input size would be  `N x H x W x 2`. When it applies to RGB image, is that mean we should augment the input image size to `N x H x W x 6`? Thank you in advance.

**Comment by fjug** [comment]
@alex-krull @tibuch ?

**Comment by tibuch** [comment]
Hi @Vandermode 
Apologies for the delayed answer.

The input (X) should just be the normal image i.e. `N x H x W x 1` for grayscale and `N x H x W x 3` for RGB images. We decided attach the mask to the target (Y), since the mask is only used during training. In the case of a RGB image 3 additional masks are needed, because every channel gets its own mask (https://github.com/juglab/n2v/blob/7a950bc26154dbf15a7a21cf3a5fba85202124c5/csbdeep/internals/train.py#L158). This is possible because the noise is independent across channels.

It just occurred to me that our current implementation is not optimal. We mask the same pixel in all channels (https://github.com/juglab/n2v/blob/7a950bc26154dbf15a7a21cf3a5fba85202124c5/csbdeep/internals/train.py#L155-L159), which is not required. I will investigate and fix this issue.
