### ISSUE TITLE
Noise including crumple and creases in images

### ISSUE THREAD

**Issue by harnitbakshi** [juglab/n2v#62]
Hi I had a question regarding the model, is it able to remove noise such as crumpling or creases as well? If not then what kind of noises can it remove

Thanks

**Comment by tibuch** [comment]
Hi @harnitbakshi 

Noise2Void has to be trained on pixel-wise independent noise. Crumpling or creases span multiple pixels, which makes them not pixel-wise independent. Since N2V has only one picture to train, it is impossible for the network to distinguish between real structure and noise patterns. We discuss this limitation in our paper (https://arxiv.org/pdf/1811.10980.pdf) in Section __4.4 Errors and Limitations__. 

This being said, the network architecture is able to learn the removal of non-pixel-wise independent noise. But you would need a pairs of training images where the input image has crumpling or creases and the target images has no such patterns. Figure 6 in the paper illustrates this well.
