### ISSUE TITLE
N2V Patch Generation 

### ISSUE THREAD

**Issue by tibuch** [juglab/n2v#73]
It is not possible to create patches which have the same size as the input data.

It looks like the error is somewhere in [here](https://github.com/juglab/n2v/blob/master/n2v/internals/N2V_DataGenerator.py#L196-L200). Probably a +1 or >= is missing.

**Comment by tibuch** [comment]
A test covering this issue is also required.

**Comment by Romain-Laine** [comment]
I have found the same issue independently by comparing the number of patches expected to the number of patches calculated by N2V, when the image size is exactly divisible by the patch size.
This issue looks to me like it's to do with range(start, stop, step), not including 'stop'.

<img width="856" alt="Screen Shot 2020-04-16 at 10 11 36" src="https://user-images.githubusercontent.com/21193399/79437909-c0069680-7fca-11ea-8de9-b646e4b567bd.png">

I think it could be fixed by replacing:
`for z in range(0, data.shape[1] - shape[0],  shape[0]):`
by
`for z in range(0, data.shape[1] - shape[0] + 1,  shape[0]):`

(same for all dimensions)

**Comment by turekg** [comment]
Fixed new version released v0.1.11
